// openings.js - Cờ Tướng Opening Database
// Coordinates: [row, col], row 0=top(Black), row 9=bottom(Red), col 0-8

const OPENINGS = [
{id:"tp_hx_bpm",category:"Pháo đầu đối Bình phong mã",name:"Trung pháo hoành xa đối Bình phong mã",
description:"Trung pháo hoành xa (Triệu Quốc Vinh) - Đỏ dùng Trung pháo kết hợp hoành xa tấn công, Đen dùng Bình phong mã phòng thủ vững chắc.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc, kiểm soát cột giữa"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phòng thủ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,8],to:[0,7],explanation:"Xa 9 bình 8 - Chuyển xa chuẩn bị xuất"},
{from:[9,8],to:[8,8],explanation:"Xa 1 tiến 1 - Xuất xa phải"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Hoàn thành Bình phong mã"},
{from:[8,8],to:[8,3],explanation:"Xa 1 bình 6 - Hoành xa tấn công cánh"},
{from:[0,2],to:[2,4],explanation:"Tượng 3 tiến 5 - Phi tượng trung tâm phòng thủ"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 - Tiến tốt mở đường cho mã"},
{from:[7,1],to:[7,0],explanation:"Pháo 8 bình 9 - Pháo chuyển cánh phối hợp"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 - Bổ sĩ bảo vệ tướng"}]},

{id:"tp_tx_bpm",category:"Pháo đầu đối Bình phong mã",name:"Trung pháo trực xa đối Bình phong mã",
description:"Trung pháo trực xa (Liễu Đại Hoa) - Đỏ dùng Trung pháo với trực xa gây áp lực trực tiếp lên trung lộ.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc, kiểm soát cột giữa"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phòng thủ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,8],to:[0,7],explanation:"Xa 9 bình 8 - Chuyển xa chuẩn bị xuất"},
{from:[9,8],to:[9,7],explanation:"Xa 1 bình 2 - Chuyển xe chuẩn bị trực xa"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Hoàn thành Bình phong mã"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 - Tiến binh mở đường cho mã"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 - Tiến tốt giành không gian"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[2,7],to:[2,8],explanation:"Pháo 8 bình 9 - Pháo chuyển cánh phối hợp"}
]},

{id:"tp_t3b_bpm",category:"Pháo đầu đối Bình phong mã",name:"Trung pháo tiến tam binh đối Bình phong mã",
description:"Trung pháo tiến tam binh (Dương Quan Lân) - Đỏ tiến binh 3 sớm kết hợp Trung pháo, tạo thế tấn công linh hoạt.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Bình phong mã"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 - Đen pháo vào giữa trước khi lên mã"},
{from:[6,6],to:[5,6],explanation:"Binh 3 tiến 1 - Tiến binh 3, mở đường cho Mã"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Hoàn thành Bình phong mã"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Mã nhảy qua binh vừa tiến"},
{from:[3,2],to:[4,2],explanation:"Tốt 3 tiến 1 - Đen tiến tốt đối kháng"},
{from:[9,0],to:[8,0],explanation:"Xa 9 tiến 1 - Đỏ xuất xa trái"},
{from:[0,8],to:[1,8],explanation:"Xa 9 tiến 1 - Đen xuất xa"}
]},

{id:"tp_qhx_bpm",category:"Pháo đầu đối Bình phong mã",name:"Trung pháo quá hà xa đối Bình phong mã",
description:"Trung pháo quá hà xa (Dương Quan Lân) - Đỏ đưa Xa qua hà tấn công sớm, gây áp lực lớn lên Đen.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phòng thủ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,8],to:[0,7],explanation:"Xa 9 bình 8 - Đen chuyển xe đối kháng"},
{from:[9,8],to:[9,7],explanation:"Xa 1 bình 2 - Chuyển xe chuẩn bị xuất"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Hoàn thành Bình phong mã"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 - Tiến binh mở đường"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 - Đen tiến tốt giành không gian"},
{from:[9,7],to:[3,7],explanation:"Xa 2 tiến 6 - Quá hà xa! Xe vượt sông tấn công"},
{from:[2,7],to:[2,8],explanation:"Pháo 8 bình 9 - Pháo chuyển cánh phối hợp"},
{from:[3,7],to:[3,6],explanation:"Xa 2 bình 3 - Xa chuyển cánh tấn công"},
{from:[2,8],to:[1,8],explanation:"Pháo 9 thoái 1 - Pháo lui phòng thủ"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 - Bổ sĩ bảo vệ tướng"},
{from:[6,4],to:[5,4],explanation:"Binh 5 tiến 1 - Tiến binh trung tâm giành không gian"},
{from:[1,8],to:[1,6],explanation:"Pháo 9 bình 7 - Pháo chuyển sang cánh phối hợp"}
]},

{id:"n7p_bpm",category:"Pháo đầu đối Bình phong mã",name:"Ngũ thất pháo đối Bình phong mã",
description:"Ngũ thất pháo (Lưu Điện Trung) - Đỏ dùng thế Ngũ thất pháo (Pháo ở cột 5 và cột 7) tấn công cánh phải.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phòng thủ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 - Chuẩn bị xuất xe"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 - Chuyển xe chuẩn bị xuất"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Hoàn thành Bình phong mã"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 - Tiến binh mở đường"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 - Tiến tốt tranh giành trung tâm"},
{from:[7,1],to:[7,2],explanation:"Pháo 8 bình 7 - Tạo thế Ngũ thất pháo, hai pháo cột 5 và 7"},
{from:[0,2],to:[2,4],explanation:"Tượng 3 tiến 5 - Phi tượng trung tâm phòng thủ"}
]},

{id:"tp_thp_hx",category:"Pháo đầu đối Thuận pháo",name:"Thuận pháo hoành xa đối trực xa",
description:"Thuận pháo hoành xa (Triệu Quốc Vinh) - Cả hai bên đều dùng Trung pháo cùng hướng. Đỏ kết hợp hoành xa, Đen dùng trực xa.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 - Thuận pháo, pháo cùng hướng"},
{from:[9,8],to:[8,8],explanation:"Xa 1 tiến 1 - Xuất xa phải"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phòng thủ"},
{from:[8,8],to:[8,3],explanation:"Xa 1 bình 6 - Hoành xa tấn công cánh"},
{from:[0,8],to:[0,7],explanation:"Xa 9 bình 8 - Chuyển xa chuẩn bị xuất"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,7],to:[4,7],explanation:"Xa 8 tiến 4 - Trực xa tiến sâu"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Khai triển mã phòng thủ"},
{from:[8,3],to:[3,3],explanation:"Xa 6 tiến 5 - Xa quá hà tấn công"},
{from:[2,4],to:[2,5],explanation:"Pháo 5 bình 6 - Pháo chuyển cánh phối hợp"}
]},

{id:"tp_thp_tx",category:"Pháo đầu đối Thuận pháo",name:"Thuận pháo trực xa đối hoành xa",
description:"Thuận pháo trực xa (Triệu Quốc Vinh) - Đỏ dùng trực xa tấn công trung lộ, Đen phản công bằng hoành xa.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 - Thuận pháo"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phòng thủ"},
{from:[9,8],to:[9,7],explanation:"Xa 1 bình 2 - Chuyển xe chuẩn bị xuất"},
{from:[0,8],to:[1,8],explanation:"Xa 9 tiến 1 - Xuất xe"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Hoàn thành bình phong mã"},
{from:[6,6],to:[5,6],explanation:"Binh 3 tiến 1 - Tiến binh mở đường cho mã"},
{from:[1,8],to:[1,3],explanation:"Xa 9 bình 4 - Hoành xa chuyển sang trung lộ phản công"}
]},

{id:"tp_thp_ldx",category:"Pháo đầu đối Thuận pháo",name:"Thuận pháo lưỡng đầu xà",
description:"Thuận pháo lưỡng đầu xà (Triệu Quốc Vinh) - Biến thể Thuận pháo với thế Lưỡng đầu xà, hai Xa đều xuất ra sớm như hai đầu rắn.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 - Thuận pháo"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã"},
{from:[9,8],to:[9,7],explanation:"Xa 1 bình 2 - Hậu đi hoành xa"},
{from:[0,8],to:[1,8],explanation:"Xa 9 tiến 1 - Xuất xa"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Lên mã trong, tránh tốt biên cản"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Khai triển mã"},
{from:[6,6],to:[5,6],explanation:"Binh 3 tiến 1 - Hình thành Lưỡng đầu xà, hai binh cùng tiến"},
{from:[3,2],to:[4,2],explanation:"Tốt 3 tiến 1 - Hai tốt cùng tiến, Lưỡng đầu xà"}]},

{id:"tp_nghp_txhx",category:"Pháo đầu đối Nghịch pháo",name:"Nghịch pháo trực xa",
description:"Nghịch pháo trực xa (Hồ Vinh Hoa) - Đen dùng Nghịch pháo (pháo ngược hướng Đỏ) kết hợp phòng thủ linh hoạt.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc"},
{from:[2,1],to:[2,4],explanation:"Pháo 2 bình 5 - Nghịch pháo đối xứng"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,7],to:[2,8],explanation:"Mã 8 tiến 9 - Mã khai triển ra biên"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 - Trực xa chuẩn bị xuất"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 - Chuyển xe chuẩn bị xuất"},
{from:[9,7],to:[5,7],explanation:"Xe 2 tiến 4 - Trực xa tiến sát hà, chuẩn bị tấn công"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Khai triển mã trái"},
{from:[9,1],to:[7,0],explanation:"Mã 8 tiến 9 - Mã khai triển ra biên"},
{from:[0,0],to:[0,1],explanation:"Xe 1 bình 2 - Chuyển xe chuẩn bị xuất"},
{from:[9,0],to:[9,1],explanation:"Xe 9 bình 8 - Chuyển xe chuẩn bị xuất"},
{from:[0,1],to:[4,1],explanation:"Xe 2 tiến 4 - Trực xa tiến sát hà, đối xứng phản công"}]},

{id:"tp_lietp",category:"Pháo đầu đối Nghịch pháo",name:"Liệt pháo",
description:"Đại Liệt Pháo (Hồ Vinh Hoa) - Hai bên cùng vào Pháo đầu, Nghịch pháo đối công toàn diện với Trực xa quá hà.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc"},
{from:[2,1],to:[2,4],explanation:"Pháo 2 bình 5 - Nghịch pháo đối công"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,7],to:[2,8],explanation:"Mã 8 tiến 9 - Mã khai triển ra biên"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 - Trực xa chuẩn bị xuất"},
{from:[2,7],to:[2,5],explanation:"Pháo 8 bình 6 - Liệt pháo, pháo chiếm lộ 6"},
{from:[9,7],to:[1,7],explanation:"Xe 2 tiến 8 - Xa xông thẳng áp sát cung đối phương"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Khai triển mã trái"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 - Tiến binh mở đường"},
{from:[0,0],to:[0,1],explanation:"Xe 1 bình 2 - Chuyển xe chuẩn bị xuất"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[0,1],to:[6,1],explanation:"Xe 2 tiến 6 - Xa quá hà tấn công sâu"}]},

{id:"tp_bdlp",category:"Pháo đầu đối Nghịch pháo",name:"Bán đồ liệt pháo",
description:"Bán đồ Liệt Pháo (Hồ Vinh Hoa) - Đen nhảy Mã trước rồi mới vào Pháo đầu, giữ nhịp chờ chiến thuật linh hoạt.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Nhảy mã trước, chưa đáp pháo"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 - Tiến tốt mở đường"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 - Trực xa chuẩn bị xuất"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 - Bán đồ liệt pháo hình thành"},
{from:[9,7],to:[3,7],explanation:"Xe 2 tiến 6 - Xa quá hà ép sát hàng tốt"},
{from:[3,2],to:[4,2],explanation:"Tốt 3 tiến 1 - Tiến tốt tranh giành trung tâm"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Hoàn thiện song chính mã"},
{from:[9,0],to:[8,0],explanation:"Xe 9 tiến 1 - Xuất xe trái"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 - Bổ sĩ bảo vệ tướng"}]},


{id:"tp_ddm_hx",category:"Pháo đầu đối Đơn đề mã",name:"Đơn đề mã hoành xa",
description:"Đơn đề mã hoành xa (Hứa Ngân Xuyên) - Đen chỉ lên một Mã kết hợp hoành xa phản công linh hoạt.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Đơn đề mã, chỉ lên một mã"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,7],to:[2,8],explanation:"Mã 8 tiến 9 - Mã khai triển ra biên"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 - Trực xa chuẩn bị xuất"},
{from:[2,7],to:[2,5],explanation:"Pháo 8 bình 6 - Pháo giữ cánh phối hợp"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[0,8],to:[1,8],explanation:"Xe 9 tiến 1 - Xuất xe chuẩn bị hoành xa"},
{from:[6,4],to:[5,4],explanation:"Binh 5 tiến 1 - Tiến trung binh gây áp lực"},
{from:[0,2],to:[2,4],explanation:"Tượng 3 tiến 5 - Phi tượng trung tâm phòng thủ"}
]},

{id:"tp_ddm_gp",category:"Pháo đầu đối Đơn đề mã",name:"Đơn đề mã giáp pháo",
description:"Đơn đề mã giáp pháo (Hứa Ngân Xuyên) - Đơn đề mã kết hợp giáp pháo phòng thủ kiên cố.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 — Trung pháo khai cuộc"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Đơn đề mã, chỉ lên một Mã"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Phát triển Mã cánh phải"},
{from:[0,7],to:[2,8],explanation:"Mã 8 tiến 9 — Mã khai triển ra biên"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 — Xuất Trực xa"},
{from:[0,8],to:[1,8],explanation:"Xe 9 tiến 1 — Nhấc Xe chuẩn bị chuyển cánh"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 — Tiến Binh mở đường cho Mã"},
{from:[1,8],to:[1,3],explanation:"Xe 9 bình 4 — Hoành xa sang lộ 4 chiếm vị trí"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 — Phát triển Mã trái"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 — Bổ Sĩ củng cố phòng thủ"},
{from:[7,1],to:[7,0],explanation:"Pháo 8 bình 9 — Bình Pháo ra biên mở đường cho Xe"},
{from:[2,7],to:[2,6],explanation:"Pháo 8 bình 7 — Pháo chuyển cánh phối hợp"},
{from:[9,0],to:[9,1],explanation:"Xe 9 bình 8 — Xuất nốt Xe trái"},
{from:[0,0],to:[1,0],explanation:"Xe 1 tiến 1 — Nhấc Xe chuẩn bị xuất quân"}]},

{id:"tp_pcm_cb",category:"Pháo đầu đối Phản cung mã",name:"Phản cung mã cơ bản",
description:"Phản cung mã (Hồ Vinh Hoa) - Mã nhảy về phía cung (sĩ tượng), phòng thủ rồi phản công.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7"},
{from:[0,8],to:[1,8],explanation:"Xa 9 tiến 1 - Xuất xa"},
{from:[9,0],to:[8,0],explanation:"Xa 9 tiến 1"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 - Tiến tốt mở đường cho mã"},
{from:[8,0],to:[8,3],explanation:"Xa 9 bình 6"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 - Bổ sĩ bảo vệ tướng"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3"},
{from:[2,1],to:[2,3],explanation:"Pháo 2 bình 4 - Pháo giữ cánh phối hợp mã"}
]},

{id:"tp_pcm_px",category:"Pháo đầu đối Phản cung mã",name:"Phản cung mã đối pháo đầu trực xa",
description:"Phản cung mã tả pháo phong xa (Hồ Vinh Hoa) - Biến thể dùng pháo trái phong tỏa xa đối phương.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Phản cung mã"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[2,7],to:[2,5],explanation:"Pháo 8 bình 6 - Tả pháo phong xa"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 - Trực xa chuẩn bị xuất"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 - Tiến binh mở đường"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 - Tiến tốt tranh giành trung tâm"},
{from:[7,1],to:[7,3],explanation:"Pháo 8 bình 6 - Song pháo lộ 6 gây áp lực"},
{from:[0,8],to:[1,8],explanation:"Xe 9 tiến 1 - Xuất xe chuẩn bị hoành xa"}
]},

{id:"tp_n6p",category:"Pháo đầu - Biến thể đặc biệt",name:"Ngũ lục pháo",
description:"Ngũ lục pháo (Hồ Vinh Hoa) - Hai pháo ở cột 5 và cột 6, tập trung hỏa lực tấn công cánh.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 — Trung pháo khai cuộc"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Khai triển mã phòng thủ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Phát triển Mã cánh phải"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 — Xuất Trực xa đối kháng"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 — Xuất Trực xa"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Hoàn thành Bình phong mã"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 — Tiến Binh mở đường cho Mã"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 — Tiến tốt giành không gian"},
{from:[7,1],to:[7,3],explanation:"Pháo 8 bình 6 — Tạo thế Ngũ lục pháo (cột 5 và 6)"},
{from:[0,2],to:[2,4],explanation:"Tượng 3 tiến 5 — Phi Tượng trung tâm phòng thủ"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 — Khai triển Mã trái"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 — Bổ Sĩ bảo vệ tướng"}
]},

{id:"tp_pcm_ht",category:"Pháo đầu đối Phản cung mã",name:"Phản cung mã hữu tượng",
description:"Phản cung mã hữu tượng (Hồ Vinh Hoa) - Kết hợp phi Tượng phải và Pháo giữ cánh, phòng thủ vững chắc.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 — Trung pháo khai cuộc"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Phản cung mã"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Phát triển Mã cánh phải"},
{from:[2,7],to:[2,5],explanation:"Pháo 8 bình 6 — Pháo giữ cánh phối hợp"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 — Xuất Trực xa"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Đen lập xong Phản Cung Mã"},
{from:[9,7],to:[3,7],explanation:"Xe 2 tiến 6 — Quá hà xa gây áp lực từ sớm"},
{from:[0,2],to:[2,4],explanation:"Tượng 3 tiến 5 — Phi Tượng trung tâm, củng cố phòng thủ"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 — Tiến Binh mở đường cho Mã"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 — Xuất Trực xa đối kháng"},
{from:[3,7],to:[3,6],explanation:"Xe 2 bình 3 — Bình Xe ăn Tốt gây áp lực"},
{from:[0,7],to:[2,7],explanation:"Xe 8 tiến 2 — Dâng Xe chuẩn bị phản công"}]},

{id:"tp_n7p_t3b",category:"Pháo đầu - Biến thể đặc biệt",name:"Ngũ thất pháo tiến tam binh",
description:"Ngũ thất pháo tiến tam binh (Lưu Điện Trung) - Kết hợp tiến binh 3, mở đường cho mã tấn công cánh phải.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 — Trung pháo khai cuộc"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Khai triển mã phòng thủ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Phát triển Mã cánh phải"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 — Xuất Trực xa đối kháng"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 — Xuất Trực xa"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Hoàn thành Bình phong mã"},
{from:[6,6],to:[5,6],explanation:"Binh 3 tiến 1 — Tiến tam binh mở đường"},
{from:[3,2],to:[4,2],explanation:"Tốt 3 tiến 1 — Tiến tốt đối kháng"},
{from:[9,1],to:[7,0],explanation:"Mã 8 tiến 9 — Mã khai triển cánh"},
{from:[0,2],to:[2,4],explanation:"Tượng 3 tiến 5 — Phi Tượng trung tâm phòng thủ"},
{from:[7,1],to:[7,2],explanation:"Pháo 8 bình 7 — Tạo thế Ngũ thất pháo (cột 5 và 7)"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 — Bổ Sĩ bảo vệ tướng"},
{from:[9,0],to:[9,1],explanation:"Xe 9 bình 8 — Xuất Xe cánh trái"},
{from:[0,0],to:[0,1],explanation:"Xe 1 bình 2 — Đen chuyển Xe chuẩn bị xuất"},
{from:[9,7],to:[3,7],explanation:"Xe 2 tiến 6 — Quá hà xa! Xe vượt sông tấn công"},
{from:[2,7],to:[1,7],explanation:"Pháo 8 thoái 1 — Pháo lui phòng thủ"}
]},

{id:"ptc_ttp",category:"Phi tượng cục",name:"Phi tượng cục đối tả trung pháo",
description:"Phi tượng cục (Hồ Vinh Hoa) - Đỏ khai cuộc bằng Phi tượng, Đen phản công bằng pháo vào trung lộ từ cánh trái.",
moves:[
{from:[9,6],to:[7,4],explanation:"Tượng 3 tiến 5 - Phi tượng cục khai cuộc"},
{from:[2,1],to:[2,4],explanation:"Pháo 2 bình 5 - Đen trung pháo phản công"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Khai triển mã"},
{from:[6,6],to:[5,6],explanation:"Binh 3 tiến 1 - Tiến binh mở đường"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phải"},
{from:[7,7],to:[7,5],explanation:"Pháo 2 bình 4 - Pháo chuyển cánh phối hợp"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 - Xuất xe chuẩn bị"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[3,2],to:[4,2],explanation:"Tốt 3 tiến 1 - Tiến tốt tranh giành trung tâm"}
]},

{id:"ptc_htp",category:"Phi tượng cục",name:"Phi tượng cục đối hữu trung pháo",
description:"Phi tượng cục (Hồ Vinh Hoa) - Đen dùng pháo phải vào trung lộ tạo áp lực.",
moves:[
{from:[9,6],to:[7,4],explanation:"Tượng 3 tiến 5 - Phi tượng cục"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 - Đen trung pháo từ cánh phải"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7"},
{from:[7,7],to:[7,5],explanation:"Pháo 2 bình 4 - Pháo giữ cánh"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3"},
{from:[9,0],to:[8,0],explanation:"Xa 9 tiến 1"},
{from:[0,0],to:[1,0],explanation:"Xa 1 tiến 1"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3"},
{from:[3,4],to:[4,4],explanation:"Tốt 5 tiến 1"}
]},

{id:"ptc_tt",category:"Phi tượng cục",name:"Phi tượng cục đối tiến tốt",
description:"Phi tượng cục (Hồ Vinh Hoa) - Đen đáp trả bằng tiến tốt, giành không gian từ từ.",
moves:[
{from:[9,6],to:[7,4],explanation:"Tượng 3 tiến 5 - Phi tượng cục khai cuộc"},
{from:[3,2],to:[4,2],explanation:"Tốt 3 tiến 1 - Tiến tốt thăm dò"},
{from:[7,1],to:[7,2],explanation:"Pháo 8 bình 7 - Pháo chuyển cánh phối hợp"},
{from:[0,1],to:[2,0],explanation:"Mã 2 tiến 1 - Mã khai triển ra biên"},
{from:[9,1],to:[7,0],explanation:"Mã 8 tiến 9 - Mã khai triển ra biên"},
{from:[0,0],to:[0,1],explanation:"Xe 1 bình 2 - Chuyển xe chuẩn bị xuất"},
{from:[6,0],to:[5,0],explanation:"Binh 9 tiến 1 - Tiến binh mở đường"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 - Trung pháo phản công"},
{from:[9,0],to:[8,0],explanation:"Xe 9 tiến 1 - Xuất xe trái"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phòng thủ"}
]},

{id:"tncl_tcb",category:"Tiên nhân chỉ lộ",name:"Tiên nhân chỉ lộ đối tốt",
description:"Tiên nhân chỉ lộ (Hứa Ngân Xuyên) - Đỏ tiến binh đầu tiên thăm dò, Đen đối tốt đáp trả. Đỏ dùng hoành xa tấn công sâu.",
moves:[
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 — Tiên nhân chỉ lộ, thăm dò đối phương"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 — Đối tốt, Đen cũng tiến tốt đáp trả"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 — Khai triển Mã trái"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Khai triển mã phòng thủ"},
{from:[9,0],to:[8,0],explanation:"Xe 9 tiến 1 — Nhấc Xe chuẩn bị chuyển cánh"},
{from:[0,2],to:[2,4],explanation:"Tượng 3 tiến 5 — Phi Tượng trung tâm phòng thủ"},
{from:[9,6],to:[7,4],explanation:"Tượng 3 tiến 5 — Phi Tượng trung tâm"},
{from:[0,1],to:[1,3],explanation:"Mã 2 tiến 4 — Mã nhảy phản cung, chuẩn bị phối hợp"},
{from:[8,0],to:[8,5],explanation:"Xe 9 bình 4 — Hoành xa sang lộ 4 tấn công"},
{from:[0,0],to:[0,2],explanation:"Xe 1 bình 3 — Đen chuyển Xe phối hợp phòng thủ"},
{from:[8,5],to:[1,5],explanation:"Xe 4 tiến 7 — Xe tiến sâu vào trận địa đối phương"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 — Bổ Sĩ bảo vệ tướng"}
]},

{id:"tncl_tp",category:"Tiên nhân chỉ lộ",name:"Tiên nhân chỉ lộ đối trung pháo",
description:"Tiên nhân chỉ lộ (Hứa Ngân Xuyên) - Đen đáp trả bằng trung pháo, Đỏ phản công bằng Pháo quá hà và Trung pháo.",
moves:[
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 — Tiên nhân chỉ lộ, thăm dò đối phương"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 — Đen trung pháo phản công mạnh mẽ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Phát triển Mã cánh phải"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Khai triển mã phòng thủ"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 — Xuất Trực xa"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 — Xuất Trực xa đối kháng"},
{from:[7,7],to:[3,7],explanation:"Pháo 2 tiến 4 — Pháo quá hà! Tiến sâu gây áp lực"},
{from:[2,1],to:[2,2],explanation:"Pháo 2 bình 3 — Tốt để pháo, phòng thủ linh hoạt"},
{from:[7,1],to:[7,4],explanation:"Pháo 8 bình 5 — Đỏ cũng Trung pháo, đối công toàn diện"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 — Tiến tốt giành không gian"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 — Khai triển Mã trái, hoàn thiện đội hình"},
{from:[3,2],to:[4,2],explanation:"Tốt 3 tiến 1 — Tiến tốt mở đường cho mã"}
]},

{id:"tncl_pt",category:"Tiên nhân chỉ lộ",name:"Tiên nhân chỉ lộ đối phi tượng",
description:"Tiên nhân chỉ lộ (Hứa Ngân Xuyên) - Đen phi tượng đáp trả, xây dựng thế trận chặt chẽ.",
moves:[
{from:[6,6],to:[5,6],explanation:"Binh 3 tiến 1 - Tiên nhân chỉ lộ"},
{from:[0,2],to:[2,4],explanation:"Tượng 3 tiến 5 - Phi tượng trung tâm"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3"},
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Chuyển sang trung pháo"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7"},
{from:[9,0],to:[8,0],explanation:"Xa 9 tiến 1"},
{from:[3,4],to:[4,4],explanation:"Tốt 5 tiến 1"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3"},
{from:[0,0],to:[1,0],explanation:"Xa 1 tiến 1"}
]},

{id:"kmc_tt",category:"Khởi mã cục",name:"Khởi mã cục đối tiến tốt",
description:"Khởi mã cục (Lữ Khâm) - Đỏ khởi mã chuyển sĩ giác pháo, Đen tiến tốt đối kháng.",
moves:[
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 — Khởi mã cục, khai cuộc bằng Mã"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 — Tiến tốt cánh đối kháng"},
{from:[7,7],to:[7,5],explanation:"Pháo 2 bình 4 — Pháo giữ cánh phối hợp"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Khai triển mã phòng thủ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Phát triển Mã cánh phải"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Hoàn thành Bình phong mã"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 — Xuất Trực xa"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 — Xuất Trực xa đối kháng"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 — Tiến binh mở đường cho Mã"},
{from:[0,2],to:[2,4],explanation:"Tượng 3 tiến 5 — Phi Tượng trung tâm phòng thủ"},
{from:[9,0],to:[8,0],explanation:"Xe 9 tiến 1 — Nhấc Xe chuẩn bị chuyển cánh"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 — Bổ Sĩ bảo vệ tướng"},
{from:[8,0],to:[8,3],explanation:"Xe 9 bình 6 — Hoành xa chiếm lộ tấn công"},
{from:[0,0],to:[0,3],explanation:"Xe 1 bình 4 — Đen chuyển Xe giữ cánh phối hợp"}
]},

{id:"kmc_tp",category:"Khởi mã cục",name:"Khởi mã cục đối trung pháo",
description:"Khởi mã cục (Lữ Khâm) - Đỏ khởi mã chuyển sĩ giác pháo, Đen đáp trả bằng trung pháo gây áp lực trung lộ.",
moves:[
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 — Khởi mã cục, khai cuộc bằng Mã"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 — Đen trung pháo phản công"},
{from:[7,7],to:[7,5],explanation:"Pháo 2 bình 4 — Sĩ giác pháo, pháo giữ cánh"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Khai triển mã phòng thủ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Phát triển Mã cánh phải"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Hoàn thành Bình phong mã"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 — Xuất Trực xa"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 — Xuất Trực xa đối kháng"},
{from:[9,6],to:[7,4],explanation:"Tượng 3 tiến 5 — Phi Tượng trung tâm"},
{from:[0,0],to:[1,0],explanation:"Xe 1 tiến 1 — Nhấc Xe chuẩn bị chuyển cánh"},
{from:[9,0],to:[8,0],explanation:"Xe 9 tiến 1 — Xuất Xe cánh trái"},
{from:[3,4],to:[4,4],explanation:"Tốt 5 tiến 1 — Tiến tốt trung tâm giành không gian"}
]},

{id:"kmc_ctp",category:"Khởi mã cục",name:"Khởi mã chuyển trung pháo",
description:"Khởi mã chuyển trung pháo (Lữ Khâm) - Khởi mã rồi chuyển sang trung pháo, kết hợp ưu thế của cả hai thế trận.",
moves:[
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 — Khởi mã cục, khai cuộc bằng Mã"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Khai triển mã phòng thủ"},
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 — Chuyển sang trung pháo, kết hợp hai thế trận"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Hoàn thành Bình phong mã"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Phát triển Mã cánh phải"},
{from:[0,8],to:[1,8],explanation:"Xe 9 tiến 1 — Nhấc Xe chuẩn bị chuyển cánh"},
{from:[9,0],to:[8,0],explanation:"Xe 9 tiến 1 — Xuất Xe cánh trái"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 — Tiến tốt mở đường cho mã"},
{from:[8,0],to:[8,3],explanation:"Xe 9 bình 6 — Hoành xa chiếm lộ tấn công"},
{from:[1,8],to:[1,5],explanation:"Xe 9 bình 6 — Hoành xa chiếm lộ phối hợp"}
]},

{id:"stc_sgp",category:"Sĩ tượng cục",name:"Sĩ giác pháo",
description:"Sĩ giác pháo (Hứa Ngân Xuyên) - Bổ Sĩ khai cuộc rồi lui Pháo về giác Sĩ, thế trận phòng ngự vững chắc chờ phản công.",
moves:[
{from:[9,5],to:[8,4],explanation:"Sĩ 4 tiến 5 — Bổ Sĩ khai cuộc, đặc trưng Sĩ tượng cục"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 — Đen Trung pháo tấn công trung lộ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Khai triển Mã phải bảo vệ trung binh"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Đen khai triển Mã"},
{from:[7,7],to:[8,7],explanation:"Pháo 2 thoái 1 — Pháo lui về giác Sĩ, tạo thế Sĩ giác pháo"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Đen hoàn thành Bình phong mã"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 — Khai triển Mã trái"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 — Đen xuất Trực xa"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 — Xuất Trực xa đối kháng"},
{from:[0,7],to:[4,7],explanation:"Xe 8 tiến 4 — Trực xa tiến sâu uy hiếp"}]},

{id:"stc_qbp",category:"Sĩ tượng cục",name:"Quy bối pháo",
description:"Quy bối pháo (Lại Lý Huynh) - Pháo đặt sau lưng Sĩ như mai rùa, phòng ngự cực vững rồi phản công.",
moves:[
{from:[9,5],to:[8,4],explanation:"Sĩ 4 tiến 5 — Bổ Sĩ khai cuộc"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 — Đen Trung pháo tấn công"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Khai triển Mã phải bảo vệ trung binh"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Đen khai triển Mã"},
{from:[7,7],to:[8,7],explanation:"Pháo 2 thoái 1 — Pháo lui chuẩn bị Quy bối"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Đen hoàn thành Bình phong mã"},
{from:[8,7],to:[8,5],explanation:"Pháo 2 bình 4 — Quy bối pháo! Pháo nằm sau lưng Sĩ như mai rùa"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 — Đen xuất Trực xa"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 — Khai triển Mã trái"},
{from:[3,4],to:[4,4],explanation:"Tốt 5 tiến 1 — Tiến tốt trung tâm giành không gian"}]},

{id:"qcp_bpm",category:"Quá cung pháo",name:"Quá cung pháo đối Bình phong mã",
description:"Quá cung pháo - Pháo đi qua cung sang cánh trái (Pháo 2 bình 6), kết hợp song mã tấn công. Đen dùng Bình phong mã phòng thủ.",
moves:[
{from:[7,7],to:[7,3],explanation:"Pháo 2 bình 6 - Quá cung pháo khai cuộc"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phòng thủ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 - Xuất xe chuẩn bị"},
{from:[6,6],to:[5,6],explanation:"Binh 3 tiến 1 - Tiến binh mở đường"},
{from:[3,2],to:[4,2],explanation:"Tốt 3 tiến 1 - Tiến tốt tranh giành"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 - Trực xa chuẩn bị xuất"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Hoàn thành Bình phong mã"},
{from:[9,1],to:[7,0],explanation:"Mã 8 tiến 9 - Mã khai triển ra biên"},
{from:[0,0],to:[1,0],explanation:"Xe 1 tiến 1 - Xuất xe chuẩn bị"}]},

{id:"qcp_tp",category:"Quá cung pháo",name:"Quá cung pháo đối trung pháo",
description:"Quá cung pháo đối trung pháo - Đỏ dùng Quá cung pháo, Đen phản công bằng Trung pháo mạnh mẽ, tạo thế đối đầu kịch tính.",
moves:[
{from:[7,1],to:[7,5],explanation:"Pháo 8 bình 4 - Quá cung pháo, pháo đi qua cung"},
{from:[2,1],to:[2,4],explanation:"Pháo 2 bình 5 - Đen trung pháo phản công"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Khai triển mã"},
{from:[9,0],to:[9,1],explanation:"Xe 9 bình 8 - Chuyển xe chuẩn bị xuất"},
{from:[0,0],to:[1,0],explanation:"Xe 1 tiến 1 - Xuất xe"},
{from:[9,1],to:[5,1],explanation:"Xe 8 tiến 4 - Trực xa tiến sát hà tấn công"},
{from:[1,0],to:[1,5],explanation:"Xe 1 bình 6 - Hoành xa sang lộ 6 phản công"},
{from:[9,5],to:[8,4],explanation:"Sĩ 4 tiến 5 - Bổ sĩ bảo vệ tướng"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phòng thủ"}]},

{id:"yyp",category:"Thế trận đặc biệt",name:"Uyên ương pháo",
description:"Uyên ương pháo (Hồ Vinh Hoa) - Hai pháo kết hợp như đôi uyên ương, Trung pháo phối hợp Pháo 6 tấn công mãnh liệt.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 — Trung pháo khai cuộc"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Đen khai triển Mã"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Khai triển Mã phải"},
{from:[3,6],to:[4,6],explanation:"Tốt 7 tiến 1 — Đen tiến tốt mở đường cho Mã"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 — Xuất Trực xa"},
{from:[0,8],to:[2,8],explanation:"Xe 9 tiến 2 — Đen xuất Xe dâng cao"},
{from:[9,1],to:[7,0],explanation:"Mã 8 tiến 9 — Mã biên cánh trái, chuẩn bị Uyên ương"},
{from:[2,1],to:[1,1],explanation:"Pháo 2 thoái 1 — Đen lui Pháo chuẩn bị chuyển cánh"},
{from:[7,1],to:[7,3],explanation:"Pháo 8 bình 6 — Uyên ương pháo! Hai pháo phối hợp tấn công"},
{from:[1,1],to:[1,7],explanation:"Pháo 2 bình 8 — Đen chuyển Pháo sang cánh phối hợp"},
{from:[9,7],to:[9,8],explanation:"Xe 2 bình 1 — Xe chuyển cánh chuẩn bị tấn công"},
{from:[0,0],to:[1,0],explanation:"Xe 1 tiến 1 — Đen xuất Xe cánh trái"}]},

{id:"tbh",category:"Thế trận đặc biệt",name:"Tam bộ hổ",
description:"Tam bộ hổ (Vương Thiên Nhất) - Ba nước đầu tạo thế hổ mạnh mẽ: Mã, Pháo, Xa phối hợp hoàn hảo.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 — Trung pháo khai cuộc"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 — Khai triển mã phòng thủ"},
{from:[6,6],to:[5,6],explanation:"Binh 3 tiến 1 — Tiến binh mở đường"},
{from:[0,8],to:[0,7],explanation:"Xe 9 bình 8 — Xuất Trực xa"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Khai triển Mã cánh phải"},
{from:[2,7],to:[2,8],explanation:"Pháo 8 bình 9 — Pháo chuyển biên phối hợp"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 — Tiến binh mở đường cho Mã"},
{from:[3,2],to:[4,2],explanation:"Tốt 3 tiến 1 — Tiến tốt đối kháng"},
{from:[5,2],to:[4,2],explanation:"Binh 7 tiến 1 — Ăn Tốt, binh vượt hà"},
{from:[0,7],to:[4,7],explanation:"Xe 8 tiến 4 — Xe tiến sát hà áp sát tấn công"},
{from:[4,2],to:[3,2],explanation:"Binh 7 tiến 1 — Binh tiến sâu gây áp lực"},
{from:[0,2],to:[2,4],explanation:"Tượng 3 tiến 5 — Phi Tượng trung tâm phòng thủ"},
{from:[7,1],to:[7,3],explanation:"Pháo 8 bình 6 — Pháo chuyển cánh phối hợp tấn công"},
{from:[0,1],to:[1,3],explanation:"Mã 2 tiến 4 — Mã nhảy phản cung phản kích"}
]},

{id:"ddm_qhx",category:"Pháo đầu đối Đơn đề mã",name:"Trung pháo quá hà xa đối Đơn đề mã",
description:"Trung pháo quá hà xa đối Đơn đề mã (Hồ Vinh Hoa) - Đỏ dùng Xe quá hà kết hợp Trung pháo, Đen dùng Song Hoành Xa phản công.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 — Trung pháo uy hiếp trung lộ"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 — Nhảy Mã phải giữ Tốt đầu"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 — Phát triển Mã cánh phải"},
{from:[0,7],to:[2,8],explanation:"Mã 8 tiến 9 — Ném Mã ra biên, định hình Đơn Đề Mã"},
{from:[9,8],to:[9,7],explanation:"Xe 1 bình 2 — Xuất thẳng Xe mặt tiền"},
{from:[0,8],to:[1,8],explanation:"Xe 9 tiến 1 — Nhấc Xe thành Hoành Xa, chuẩn bị chuyển cánh"},
{from:[9,7],to:[3,7],explanation:"Xe 2 tiến 6 — Quá Hà Xa! Phóng Xe qua sông vây ép từ sớm"},
{from:[1,8],to:[1,3],explanation:"Xe 9 bình 4 — Hoành xa sang lộ 4, bảo vệ Tượng và che điểm yếu"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 — Thúc Tốt khơi thông đường Mã"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 — Lên Sĩ củng cố trung lộ, chuẩn bị giằng co"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 — Phát triển nốt Mã cánh trái"},
{from:[2,7],to:[2,6],explanation:"Pháo 8 bình 7 — Pháo sang lộ 7 nhắm Binh 3, tìm cơ hội phản kích"}]},

{id:"thp_dx",category:"Pháo đầu đối Thuận pháo",name:"Thuận pháo duyên xa",
description:"Thuận pháo duyên xa (Triệu Quốc Vinh) - Biến thể Thuận pháo với Xa di chuyển dọc theo cạnh bàn cờ.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo, thiết lập Thuận pháo"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 - Thuận pháo đối công"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Triển khai mã bảo vệ trung lộ"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Triển khai mã phòng thủ"},
{from:[9,8],to:[9,7],explanation:"Xa 1 bình 2 - Đỏ ra trực xa"},
{from:[0,8],to:[1,8],explanation:"Xa 9 tiến 1 - Đen nhấc hoành xa"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Phát triển cặp mã chính diện"},
{from:[1,8],to:[1,3],explanation:"Xa 9 bình 4 - Đưa xa sang lộ 4 chiếm sườn"},
{from:[6,6],to:[5,6],explanation:"Binh 3 tiến 1 - Tiến binh thông đường mã"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Nhảy nốt mã còn lại"},
{from:[9,0],to:[8,0],explanation:"Xa 9 tiến 1 - Nhấc hoành xa trái, chuẩn bị điều động"},
{from:[2,1],to:[4,1],explanation:"Pháo 2 tiến 2 - Tiến pháo tuần hà phong tỏa không gian"}]},

{id:"thp_hx2",category:"Pháo đầu đối Thuận pháo",name:"Thuận pháo hoành xa đối trực xa (biến 2)",
description:"Thuận pháo hoành xa biến 2 (Triệu Quốc Vinh) - Đỏ kết hợp hoành xa quá hà tấn công, Đen phản công bằng trực xa tiến sâu.",
moves:[
{from:[7,7],to:[7,4],explanation:"Pháo 2 bình 5 - Trung pháo khai cuộc"},
{from:[2,7],to:[2,4],explanation:"Pháo 8 bình 5 - Thuận pháo, pháo cùng hướng với Đỏ"},
{from:[9,7],to:[7,6],explanation:"Mã 2 tiến 3 - Khai triển mã phải"},
{from:[0,7],to:[2,6],explanation:"Mã 8 tiến 7 - Khai triển mã phòng thủ"},
{from:[9,8],to:[9,7],explanation:"Xa 1 bình 2 - Chuyển xe chuẩn bị xuất"},
{from:[0,8],to:[1,8],explanation:"Xa 9 tiến 1 - Xuất xe chuẩn bị hoành xa"},
{from:[9,1],to:[7,2],explanation:"Mã 8 tiến 7 - Khai triển mã trái"},
{from:[0,1],to:[2,2],explanation:"Mã 2 tiến 3 - Hoàn thành bình phong mã"},
{from:[6,6],to:[5,6],explanation:"Binh 3 tiến 1 - Tiến binh mở đường cho mã"},
{from:[1,8],to:[1,3],explanation:"Xa 9 bình 4 - Hoành xa chuyển sang trung lộ phản công"},
{from:[9,7],to:[3,7],explanation:"Xa 2 tiến 6 - Quá hà xa! Xe vượt sông tấn công"},
{from:[0,3],to:[1,4],explanation:"Sĩ 4 tiến 5 - Bổ sĩ bảo vệ tướng"},
{from:[3,7],to:[3,6],explanation:"Xa 2 bình 3 - Xe chuyển cánh tấn công"},
{from:[0,2],to:[2,0],explanation:"Tượng 3 tiến 1 - Phi tượng trung tâm phòng thủ"},
{from:[6,2],to:[5,2],explanation:"Binh 7 tiến 1 - Tiến binh cánh trái mở đường"},
{from:[1,3],to:[6,3],explanation:"Xa 4 tiến 5 - Xe quá hà tiến sâu phản công"}
]}
];

// Group openings by category
function getOpeningsByCategory() {
    const categories = {};
    for (const opening of OPENINGS) {
        if (!categories[opening.category]) {
            categories[opening.category] = [];
        }
        categories[opening.category].push(opening);
    }
    return categories;
}
